「CoreProtectの機能をXPhoneからうまい具合に叩けるアプリ」
XelticaMC/X-Core pull request #178
Opened 2022-12-19 15:02 UTC by Lisitsa-requin

## できること
- ログを見る(一部のみ)
- ロールバックする(一部のみ)
- インスペクトモードの切り替え
- 取得したログのページの変更
## 未実装
- ログが発生した場所が移動する機能 (座標の取得が現時点での勉強会レベルの実力では無理だと判断)
- アイテムの絞り込み(ここまでサポートするなら正直コマンド打ったほうが早い)
- ブロック分の範囲絞り込み(上記と同様)
- restoreおよびpurgeコマンド(使わないので)
- アクション:inventory、session、sign(あんまり使わない＆オンライン状態じゃないと見れないコマンドのため)

2022-12-20 18:54 UTC, EbiseLutica requested changes
@Lisitsa-requin 修正箇所にコメントしました。

X Phoneアプリのコードに書くべき処理と、モジュールのコードに書くべき処理が全て真逆の方にあったので、先にそちらを修正してから他の修正にあたると整理しやすいかと思います。

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeModule.kt
> +    }
`getGamemodeList()` `start()` メソッドの処理は、X Phone Appの `onLaunch` メソッド内に書いたほうが的確です。

逆にX Phone Appの `selectMenuItem` は対話ではない、実際の処理のためにこちらのモジュールに書いてしまいましょう。

CoreProtectGuiTestのほうも同様です。

<details>
<summary>理由</summary>

勉強会で話し足りていなかったので理由を追記します。

これらはプレイヤーと対話するための処理にあたります。こういった対話系の処理はApp/Command/Event Handlerに書き、対話の結果行われる実際の処理はModuleに、という方針でやっています。

例えば「トロッコを出すアプリ」と「トロッコを出すコマンド」を考えると、どちらも最終的に

* プレイヤーの眼前の位置を取る
* その位置にレールがあるかを判定する
  * あれば、トロッコを設置
  * 無ければエラーを出す

というコードが実行されます。このコードをアプリとコマンドそれぞれに実装するより、まとめたほうが良いのはなんとなく察しが付くかと思います。

このように、まとめたほうが良い処理は基本的にModuleに書きます。

（例に出したにもかかわらず、実際のトロッコ機能（ボート機能も含む）はまだモジュール化対応が終わっていない）
</details>

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestApp.kt
> +            }
* whenの中身は単純な式を帰す場合、 `{}` を省略できます
* もっと丁寧に書くなら、マジックナンバーみが増さないように途中式にしてしまったり、変なunitは弾くよう例外処理をするほうが良いかも

```suggestion
            "s" -> 1
            "m" -> 1 * 60
            "h" -> 1 * 60 * 60
            "d" -> 1 * 60 * 60 * 24
            "w" -> 1 * 60 * 60 * 24 * 7
            else -> throw IllegalArgumentException("Invalid unit \"${unit}\"")
```

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestModule.kt
> +            }
【質問】`let` を使用している意図はなんでしょうか…。特になければ、シンプルに `onInputPlayerName(userName, player)` で良さそうです。

他の箇所も同様です。

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeModule.kt
> +    private val app by lazy { GamemodeChangeApp() }
基本的にX Phone Appのインスタンスを2箇所で生成しないようにしてください。本事例では、モジュールに処理を移せば使わなくなるので行ごと削除で大丈夫そうです。

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestModule.kt
> +            }
`if` のほうが可読性が高いと感じました。
もし `let` & `run` を使うべき理由が特に無いのであれば、以下のよう書くことを提案します。

```suggestion
            if (value == null || value <= 0) {
                Gui.getInstance().error(player, "正しい数値を入力する必要があります。")
                return@openTextInput
            }

            app.commandSend(value, player)
```

2022-12-20 18:54 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestApp.kt
> +    var commandFirst: String = "co"
コマンド組み立て用変数だと思われますが、マルチプレイで100%衝突してしまいます。

メソッドの引数としてバケツリレー式に渡すようにしてください。

2022-12-21 07:40 UTC, Lisitsa-requin commented
@EbiseLutica 
一つ認識があやふやなところがあるので質問させてください。
> X Phoneアプリのコードに書くべき処理と、モジュールのコードに書くべき処理が全て真逆の方にあったので、先にそちらを修正してから他の修正にあたると整理しやすいかと思います。

こちらの指摘なのですが、説明の資料としてもそれらの書くべき処理の基準みたいなのが見当たらなかったのですが、そういった資料があるのであれば、こちら共有していただいても大丈夫でしょうか？

一応自分は以下のような基準で処理を記載していました。
- app に書くべき処理
    -  コールバックの処理(メニューアイテムを押下した時の処理)
    -  アプリを実行した結果(このアプリではコマンドをサーバーに送る処理)
- module に書くべき処理
    -  上記以外の処理
おそらく自分の認識が間違っているとは思いますが、上記質問の対応をお願いします 🙏

2022-12-21 07:41 UTC, Lisitsa-requin commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestModule.kt
> +            }
nullチェックのために使用していました。ただコード上に誤りがあり、ここは実質的に無駄なコードになってしまっているので後々見直します

2022-12-21 07:51 UTC, EbiseLutica commented
@Lisitsa-requin
 
> こちらの指摘なのですが、説明の資料としてもそれらの書くべき処理の基準みたいなのが見当たらなかったのですが、そういった資料があるのであれば、こちら共有していただいても大丈夫でしょうか？

モジュール化自体が進行中だったこともあり、今まで文書化をサボっていたので、資料としては現状無いです・・・が、[こちらのコメント](https://github.com/XelticaMC/X-Core/pull/178#discussion_r1053621925)に、理由としてまとめてあります

> * app に書くべき処理
>   * コールバックの処理(メニューアイテムを押下した時の処理)
>   * アプリを実行した結果(このアプリではコマンドをサーバーに送る処理)
> * module に書くべき処理
>   * 上記以外の処理

appに書くべき処理の箇所が、正確には次のようになります。

* メニューやテキスト入力など、ユーザーからの入力受け付け
  * 具体的にはGuiクラスを使ったUI表示などはこっち
* 処理の実行結果をユーザーに出力する処理
  * 場合によってはModuleの中でユーザーのチャット欄に結果を表示する場合もある

上に貼ったリンク先にもこの考え方を詳しく書いているのでご確認くださ。

2022-12-21 13:17 UTC, Lisitsa-requin commented
@EbiseLutica 
返答ありがとうございます。返答してもらってなんですが、ちょっと細かいところで疑問に思っている箇所が何か所があるので今度おてすきのタイミングで通話でいろいろ質問させてください 🙏

2022-12-22 03:17 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeApp.kt
> +    }
`Player#performCommand` 使うよりも、以下のようにプロパティ設定したほうが良いです

```suggestion
    fun selectMenuItem(gameMode: GameMode, player: Player) {
        player.gameMode = gameMode
    }
```

2023-01-30 16:31 UTC, EbiseLutica reviewed
@Lisitsa-requin コメントしました～

2023-01-30 16:31 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestModule.kt
> +        Bukkit.getLogger().info(sendCommand.toString())
コマンド実行ログはデフォルトで表示されるので、別途出力する必要はないハズ

2023-01-30 16:31 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeApp.kt
> +    }
1. private メソッドは public メソッドの下に置くよう統一しているので、 onLaunch の下に置いてください
使用箇所としても近い位置にあるので見やすくなりそう
2. ゲームモードを変えるだけのシンプルな処理なので、メソッド化しなくて良さそうです `player.gameMode = GameMode.SURVIVAL`

2023-01-30 16:31 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestApp.kt
> +}
【提案】 MenuItemを返すだけなことがわかりきっているので、各ケースの `{}` は無くしたほうがインデントが浅くなり読みやすいかも

このへんは好みになってくるので任せます

2023-01-30 16:35 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeApp.kt
> +    }
（一回目のレビューで気づけなくてすまぬ）

2023-02-09 12:02 UTC, Lisitsa-requin commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectCommand.kt
> +    var secondInputDate: Pair<Int, String> = Pair(0, "")
https://github.com/XelticaMC/X-Core/commit/58892b41ba5cb9b0954413d59fbaf364f61c30b2 にて対応

2023-02-09 12:03 UTC, Lisitsa-requin commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestModule.kt
> +        Bukkit.getLogger().info(sendCommand.toString())
https://github.com/XelticaMC/X-Core/commit/a3d2c514800cc3eac768d355cf817596fe44427e にて対応

2023-02-09 12:10 UTC, Lisitsa-requin commented on src/main/java/work/xeltica/craft/core/modules/gamemodeChange/GamemodeChangeApp.kt
> +    }
https://github.com/XelticaMC/X-Core/commit/e2cf3a7f850a7cbea0d8982f67108c53447b3a3f  https://github.com/XelticaMC/X-Core/commit/3aef99e3fb24bf54159a3e667e336fb054243cb5 にて対応
1.に関しては、メソッド化する必要もほぼほぼ無かったのでメソッド自体を削除

2023-02-09 12:22 UTC, Lisitsa-requin commented on src/main/java/work/xeltica/craft/core/modules/coreProtectGuiTest/CoreProtectGuiTestApp.kt
> +}
自分としては、条件分岐後の処理が複数行にまたがるときは `{}`を付けたい(`if`みたいに書きたい)派なので、ここは直しません 🙏

2023-02-10 15:09 UTC, Lisitsa-requin commented
@EbiseLutica 昨日疲れていて報告を忘れていました
コードレビューの指摘事項を修正したので問題無ければマージお願いします

2023-02-13 13:48 UTC, EbiseLutica commented
Files changed が更新されなくなっちゃったせいで差分が増えすぎて見れないので、たぶん大丈夫だろの体でマージしちゃいます…

![](https://pbs.twimg.com/media/Ck9_MOJWYAAR_Rm.jpg)

2023-02-13 13:48 UTC, merged