共有ワールド、共有ネザー、共有エンド、資源エンドの場合はエビパワーを付与しないように
XelticaMC/X-Core pull request #245
Opened 2023-02-18 15:04 UTC by Knit-prg

fixes #239 
共有ワールド、共有ネザー、共有エンド、資源エンドの場合はエビパワーを付与しないように

2023-02-20 11:01 UTC, EbiseLutica commented on src/main/java/work/xeltica/craft/core/modules/ebipower/EbiPowerHandler.kt
> +        val prohibitedWorlds = arrayOf("wildarea2", "wildarea2_nether", "wildarea2_the_end", "shigen_end")
イベントが発生するたびに配列を初期化するのは重たいので、privateメンバーにしといてください

2023-02-20 11:01 UTC, EbiseLutica requested changes
@Knit-prg ありがとうございます。1点だけコメントしました

2023-02-20 16:34 UTC, Knit-prg commented
@EbiseLutica レビュー反映しました、確認よろしくお願いします

2023-02-21 04:24 UTC, EbiseLutica commented
@Knit-prg 👌🏻 👌🏻 🙇🏻

2023-02-21 04:24 UTC, merged