Feature/disable livemode after 1min leaving
XelticaMC/X-Core pull request #48
Opened 2021-08-05 17:47 UTC by kumitatepazuru

resolve #31

2021-08-05 18:50 UTC, Xeltica requested changes
@kumitatepazuru ありがとうございます。1点だけお願いします。

2021-08-05 18:50 UTC, Xeltica commented on src/main/java/work/xeltica/craft/core/stores/PlayerStore.java
> +    public final Map<UUID, BossBar> liveBarMap = new HashMap<>();
ここ、「getLiveBarMap」ゲッターメソッドを追加する形でカプセル化してほしい

2021-08-05 18:50 UTC, Xeltica commented on src/main/java/work/xeltica/craft/core/stores/PlayerStore.java
> +    public final Map<UUID, BossBar> liveBarMap = new HashMap<>();
あるいは、`PlayerStore#setLiveMode` の、第一引数にUUIDを取るオーバーロードを作って `setLiveMode(playerUUID, false);` かなあ

2021-08-06 08:33 UTC, kumitatepazuru commented on src/main/java/work/xeltica/craft/core/stores/PlayerStore.java
> +    public final Map<UUID, BossBar> liveBarMap = new HashMap<>();
オーバーロードのほうが後々使えそうなので後者の方にします

2021-08-06 08:35 UTC, kumitatepazuru commented on src/main/java/work/xeltica/craft/core/stores/PlayerStore.java
> +    public final Map<UUID, BossBar> liveBarMap = new HashMap<>();
あ、でもその必要もないかも。修正します

2021-08-06 11:57 UTC, merged